In [3]:
import sys
sys.path.append('..')
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sfp_nsdsyn import *
import warnings
import itertools
warnings.filterwarnings("ignore", category=UserWarning)
pd.options.mode.chained_assignment = None
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
output_dir='/Volumes/server/Projects/sfp_nsd/derivatives'
dset='nsdsyn'
subj='subj01'
roi='V1'
vs='pRFsize'

In [7]:
subj_df_path = os.path.join(output_dir, 'dataframes', dset, f'dset-{dset}_sub-{subj}_roi-{roi}_vs-{vs}.csv')
subj_df = pd.read_csv(subj_df_path)
subj_df.head()

stim_idx  image_idx     names  w_r  w_a  phase  class_idx  freq_lvl  voxel  \
0         0        104  pinwheel  0.0  6.0    0.0          0         0     10   
1         0        104  pinwheel  0.0  6.0    0.0          0         0     11   
2         0        104  pinwheel  0.0  6.0    0.0          0         0     12   
3         0        104  pinwheel  0.0  6.0    0.0          0         0     16   
4         0        104  pinwheel  0.0  6.0    0.0          0         0     17   

  task  ...  eccentricity     angle      size  visualrois  vroinames eccrois  \
0  avg  ...      1.556064  5.030775  0.971252         2.0         V1     3.0   
1  avg  ...      1.302301  4.925383  0.693124         2.0         V1     3.0   
2  avg  ...      1.081738  4.781199  0.559847         2.0         V1     3.0   
3  avg  ...      1.473532  4.971115  0.963097         2.0         V1     3.0   
4  avg  ...      1.495256  5.002201  0.945766         2.0         V1     3.0   

   local_sf  local_ori  hemi     sub  
0  0.613683   0.318386    lh  subj01  
1  0.733263   0.212994    lh  subj01  
2  0.882773   0.068810    lh  subj01  
3  0.648055   0.258726    lh  subj01  
4  0.638639   0.289812    lh  subj01  

[5 rows x 21 columns]

In [10]:
precision_path = os.path.join(output_dir, 'dataframes', dset, 'precision', f'precision-v_dset-{dset}_sub-{subj}_roi-{roi}_vs-{vs}.csv')
precision_df = pd.read_csv(precision_path)
precision_df.head()

sub  voxel vroinames  noise_SD  sigma_v_squared
0  subj01     10        V1  0.586458         0.409426
1  subj01     11        V1  0.438531         0.223560
2  subj01     12        V1  0.480373         0.264642
3  subj01     16        V1  0.718100         0.606524
4  subj01     17        V1  0.613964         0.451716

In [14]:
df = subj_df.merge(precision_df, on=['sub','voxel','vroinames'])

In [37]:
w_avg = df.groupby(['sub', 'voxel', 'class_idx', 'vroinames']).mean().reset_index()

In [56]:
pt_path = '/Volumes/server/Projects/sfp_nsd/derivatives/sfp_model/results_2D/test3.pt'

In [38]:
w_avg.pivot('voxel', 'class_idx', 'local_ori')

class_idx        0         1         2         3         4         5   \
voxel                                                                   
10         0.318386  0.318386  0.318386  0.318386  0.318386  0.318386   
11         0.212994  0.212994  0.212994  0.212994  0.212994  0.212994   
12         0.068810  0.068810  0.068810  0.068810  0.068810  0.068810   
16         0.258726  0.258726  0.258726  0.258726  0.258726  0.258726   
17         0.289812  0.289812  0.289812  0.289812  0.289812  0.289812   
...             ...       ...       ...       ...       ...       ...   
7086       0.309419  0.309419  0.309419  0.309419  0.309419  0.309419   
7087       0.270359  0.270359  0.270359  0.270359  0.270359  0.270359   
7089       0.271274  0.271274  0.271274  0.271274  0.271274  0.271274   
7090       0.276253  0.276253  0.276253  0.276253  0.276253  0.276253   
7091       0.296889  0.296889  0.296889  0.296889  0.296889  0.296889   

class_idx        6         7         8         9   ...        18        19  \
voxel                                              ...                       
10         2.674580  2.674580  2.674580  2.674580  ...  1.103784  1.103784   
11         2.569189  2.569189  2.569189  2.569189  ...  0.998392  0.998392   
12         2.425005  2.425005  2.425005  2.425005  ...  0.854208  0.854208   
16         2.614921  2.614921  2.614921  2.614921  ...  1.044124  1.044124   
17         2.646006  2.646006  2.646006  2.646006  ...  1.075210  1.075210   
...             ...       ...       ...       ...  ...       ...       ...   
7086       2.665613  2.665613  2.665613  2.665613  ...  1.094817  1.094817   
7087       2.626553  2.626553  2.626553  2.626553  ...  1.055757  1.055757   
7089       2.627468  2.627468  2.627468  2.627468  ...  1.056672  1.056672   
7090       2.632448  2.632448  2.632448  2.632448  ...  1.061652  1.061652   
7091       2.653083  2.653083  2.653083  2.653083  ...  1.082287  1.082287   

class_idx        20        21        22        23        24        25  \
voxel                                                                   
10         1.103784  1.103784  1.103784  1.103784  3.069371  2.279789   
11         0.998392  0.998392  0.998392  0.998392  2.963980  2.174398   
12         0.854208  0.854208  0.854208  0.854208  2.819796  2.030214   
16         1.044124  1.044124  1.044124  1.044124  3.009712  2.220129   
17         1.075210  1.075210  1.075210  1.075210  3.040797  2.251215   
...             ...       ...       ...       ...       ...       ...   
7086       1.094817  1.094817  1.094817  1.094817  3.060404  2.270822   
7087       1.055757  1.055757  1.055757  1.055757  3.021344  2.231762   
7089       1.056672  1.056672  1.056672  1.056672  3.022260  2.232677   
7090       1.061652  1.061652  1.061652  1.061652  3.027239  2.237657   
7091       1.082287  1.082287  1.082287  1.082287  3.047874  2.258292   

class_idx        26        27  
voxel                          
10         1.498575  0.708993  
11         1.393184  0.603601  
12         1.249000  0.459417  
16         1.438915  0.649333  
17         1.470001  0.680419  
...             ...       ...  
7086       1.489608  0.700026  
7087       1.450548  0.660966  
7089       1.451463  0.661881  
7090       1.456443  0.666860  
7091       1.477078  0.687496  

[2308 rows x 28 columns]

In [59]:
my_dataset = model.SpatialFrequencyDataset(w_avg, beta_col='betas')
my_model = model.SpatialFrequencyModel(full_ver=True)
loss_history, model_history, losses = model.fit_model(my_model, my_dataset,
                                                      save_path=pt_path,
                                                      learning_rate=0.001, max_epoch=3,
                                                      print_every=1, loss_all_voxels=False)

**epoch no.0 loss: 0.129
**epoch no.1 loss: 0.128
**epoch no.2 loss: 0.128
**epoch no.3: Finished! final model params...
 {'sigma': 0.0384337417781353, 'slope': 0.31463325023651123, 'intercept': 0.43112248182296753, 'p_1': 0.060593124479055405, 'p_2': 0.08446389436721802, 'p_3': 0.08890348672866821, 'p_4': 0.059790268540382385, 'A_1': 0.866459310054779, 'A_2': 0.883697509765625}
Elapsed time: 0.07 sec


In [60]:
import torch
another_model = model.SpatialFrequencyModel(full_ver=True)
another_model.load_state_dict(torch.load(pt_path))
another_model.eval()
for name, param in another_model.named_parameters():
    print(f'{name}: {param}')

sigma: Parameter containing:
tensor([0.0394], requires_grad=True)
slope: Parameter containing:
tensor([0.3156], requires_grad=True)
intercept: Parameter containing:
tensor([0.4321], requires_grad=True)
p_1: Parameter containing:
tensor([0.0616], requires_grad=True)
p_2: Parameter containing:
tensor([0.0854], requires_grad=True)
p_3: Parameter containing:
tensor([0.0879], requires_grad=True)
p_4: Parameter containing:
tensor([0.0588], requires_grad=True)
A_1: Parameter containing:
tensor([0.8656], requires_grad=True)
A_2: Parameter containing:
tensor([0.8828], requires_grad=True)


In [41]:
loss_history

epoch      loss
0      0  0.096106
1      1  0.095947

In [42]:
model_history

epoch     sigma     slope  intercept      p_1       p_2       p_3  \
0      0  0.619453  0.444037   0.691521  0.08782  0.044759  0.080649   
1      1  0.620453  0.443037   0.690521  0.08682  0.043759  0.081649   

        p_4       A_1       A_2  
0  0.071719  0.294542  0.939823  
1  0.072719  0.293542  0.938823

In [69]:
old_file='/Volumes/server/Projects/sfp_nsd/derivatives/sfp_model/results_2D/model_history_dset-nsdsyn_bts-mean_full_ver-True_subj01_lr-0.0005_eph-20000_V1.h5'
new_file='/Volumes/server/Projects/sfp_nsd/derivatives/sfp_model/results_2D/nsdsyn/model-history_lr-0.0005_eph-10000_dset-nsdsyn_sub-subj01_roi-V1_vs-pRFsize.h5'

In [70]:
old_f = pd.read_hdf(old_file)
new_f = pd.read_hdf(new_file)

In [71]:
old_f.query('epoch == 19999')

epoch     sigma     slope  intercept       p_1       p_2       p_3  \
19999  19999  2.464081  0.139384   0.215651  0.028885 -0.020794 -0.262531   

            p_4       A_1       A_2  
19999 -0.014679  0.021958 -0.003817

In [66]:
new_f.query('epoch == 9999')

epoch     sigma     slope  intercept      p_1       p_2       p_3  \
9999   9999  2.374602  0.146491   0.201589  0.02126 -0.020941 -0.254096   

           p_4       A_1       A_2  
9999 -0.015825  0.023916 -0.006775

In [5]:
subj_df = pd.read_csv('/Volumes/server/Projects/sfp_nsd/derivatives/dataframes/broderick/dset-broderick_sub-wlsubj001_roi-V1_vs-pRFcenter_tfunc-corrected.csv')
precision_df = pd.read_csv('/Volumes/server/Projects/sfp_nsd/derivatives/dataframes/broderick/precision/precision-v_dset-broderick_sub-wlsubj001_roi-V1_vs-pRFsize.csv')


In [7]:
df = subj_df.merge(precision_df, on=['sub', 'vroinames', 'voxel'])


In [11]:
df.query('voxel == 0')

Unnamed: 0  Unnamed: 0.1  voxel  class_idx     betas  eccentricity  \
0            0             0      0          0  1.579265      2.565532   
1         3780          3780      0          1  0.927717      2.565532   
2         7560          7560      0          2  2.201150      2.565532   
3        11340         11340      0          3  2.780616      2.565532   
4        15120         15120      0          4  1.862685      2.565532   
5        18900         18900      0          5  2.306179      2.565532   
6        22680         22680      0          6  2.549803      2.565532   
7        26460         26460      0          7  2.625424      2.565532   
8        30240         30240      0          8  3.204638      2.565532   
9        34020         34020      0          9  2.849313      2.565532   
10       37800         37800      0         10  1.417065      2.565532   
11       41580         41580      0         11  0.814516      2.565532   
12       45360         45360      0         12  2.526020      2.565532   
13       49140         49140      0         13  2.283371      2.565532   
14       52920         52920      0         14  2.149028      2.565532   
15       56700         56700      0         15  2.401600      2.565532   
16       60480         60480      0         16  1.732854      2.565532   
17       64260         64260      0         17  2.715278      2.565532   
18       68040         68040      0         18  2.841083      2.565532   
19       71820         71820      0         19  2.280296      2.565532   
20       75600         75600      0         20  0.925520      2.565532   
21       79380         79380      0         21  1.946703      2.565532   
22       83160         83160      0         22  1.626531      2.565532   
23       86940         86940      0         23  2.481571      2.565532   
24       90720         90720      0         24  2.609891      2.565532   
25       94500         94500      0         25  2.248441      2.565532   
26       98280         98280      0         26  2.571519      2.565532   
27      102060        102060      0         27  2.059054      2.565532   
28      105840        105840      0         28  2.737165      2.565532   
29      109620        109620      0         29  2.822368      2.565532   
30      113400        113400      0         30  1.233580      2.565532   
31      117180        117180      0         31  2.228929      2.565532   
32      120960        120960      0         32  1.718205      2.565532   
33      124740        124740      0         33  2.594082      2.565532   
34      128520        128520      0         34  2.498524      2.565532   
35      132300        132300      0         35  2.155490      2.565532   
36      136080        136080      0         36  2.258766      2.565532   
37      139860        139860      0         37  1.859806      2.565532   
38      143640        143640      0         38  3.107373      2.565532   
39      147420        147420      0         39  2.621607      2.565532   
40      151200        151200      0         40  2.301526      2.565532   
41      154980        154980      0         41  1.841951      2.565532   
42      158760        158760      0         42  1.725571      2.565532   
43      162540        162540      0         43  2.502832      2.565532   
44      166320        166320      0         44  1.787221      2.565532   
45      170100        170100      0         45  1.795016      2.565532   
46      173880        173880      0         46  3.183910      2.565532   
47      177660        177660      0         47  2.206463      2.565532   

       angle      size hemi    w_r    w_a  image_idx           names  \
0   4.733885  0.454929   lh    0.0    6.0          0        pinwheel   
1   4.733885  0.454929   lh    0.0    8.0          8        pinwheel   
2   4.733885  0.454929   lh    0.0   11.0         16        pinwheel   
3   4.733885  0.454929   lh    0.0   16.0         24        pinwheel   
4   4.733885  0.4

In [12]:
df.pivot('voxel', 'class_idx', 'local_ori')


class_idx        0         1         2         3         4         5   \
voxel                                                                   
0          0.021496  0.021496  0.021496  0.021496  0.021496  0.021496   
1          0.011616  0.011616  0.011616  0.011616  0.011616  0.011616   
2          0.002687  0.002687  0.002687  0.002687  0.002687  0.002687   
3          0.020216  0.020216  0.020216  0.020216  0.020216  0.020216   
4          0.032599  0.032599  0.032599  0.032599  0.032599  0.032599   
...             ...       ...       ...       ...       ...       ...   
4003       0.152808  0.152808  0.152808  0.152808  0.152808  0.152808   
4004       0.180886  0.180886  0.180886  0.180886  0.180886  0.180886   
4005       0.201924  0.201924  0.201924  0.201924  0.201924  0.201924   
4006       0.287737  0.287737  0.287737  0.287737  0.287737  0.287737   
4007       0.176809  0.176809  0.176809  0.176809  0.176809  0.176809   

class_idx        6         7         8         9   ...        38        39  \
voxel                                              ...                       
0          0.021496  0.021496  0.021496  0.021496  ...  0.806894  0.806894   
1          0.011616  0.011616  0.011616  0.011616  ...  0.797014  0.797014   
2          0.002687  0.002687  0.002687  0.002687  ...  0.788085  0.788085   
3          0.020216  0.020216  0.020216  0.020216  ...  0.805614  0.805614   
4          0.032599  0.032599  0.032599  0.032599  ...  0.817998  0.817998   
...             ...       ...       ...       ...  ...       ...       ...   
4003       0.152808  0.152808  0.152808  0.152808  ...  0.938206  0.938206   
4004       0.180886  0.180886  0.180886  0.180886  ...  0.966284  0.966284   
4005       0.201924  0.201924  0.201924  0.201924  ...  0.987323  0.987323   
4006       0.287737  0.287737  0.287737  0.287737  ...  1.073135  1.073135   
4007       0.176809  0.176809  0.176809  0.176809  ...  0.962207  0.962207   

class_idx        40        41        42        43        44        45  \
voxel                                                                   
0          2.910535  2.643943  2.111439  1.844847  1.339738  1.073146   
1          2.900655  2.634063  2.101559  1.834967  1.329858  1.063266   
2          2.891725  2.625133  2.092629  1.826037  1.320929  1.054337   
3          2.909255  2.642663  2.110159  1.843567  1.338458  1.071867   
4          2.921638  2.655046  2.122542  1.855950  1.350842  1.084250   
...             ...       ...       ...       ...       ...       ...   
4003       3.041846  2.775254  2.242750  1.976158  1.471050  1.204458   
4004       3.069925  2.803333  2.270829  2.004237  1.499128  1.232536   
4005       3.090963  2.824371  2.291867  2.025275  1.520166  1.253575   
4006       0.035182  2.910183  2.377679  2.111087  1.605979  1.339387   
4007       3.065847  2.799255  2.266751  2.000159  1.495051  1.228459   

class_idx        46        47  
voxel                          
0          0.540642  0.274051  
1          0.530762  0.264170  
2          0.521833  0.255241  
3          0.539362  0.272771  
4          0.551746  0.285154  
...             ...       ...  
4003       0.671954  0.405362  
4004       0.700032  0.433440  
4005       0.721071  0.454479  
4006       0.806883  0.540291  
4007       0.695955  0.429363  

[3305 rows x 48 columns]

In [13]:
subj_model = model.SpatialFrequencyModel(full_ver=True)

In [14]:
my_dataset = model.SpatialFrequencyDataset(df, beta_col='betas')

In [16]:
df.groupby(['voxel', 'class_idx', 'vroinames'])['local_ori'].count()

voxel  class_idx  vroinames
0      0          V1           1
       1          V1           1
       2          V1           1
       3          V1           1
       4          V1           1
                              ..
4007   43         V1           1
       44         V1           1
       45         V1           1
       46         V1           1
       47         V1           1
Name: local_ori, Length: 158640, dtype: int64