In [1]:
import sys
sys.path.append('..')
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sfp_nsdsyn import *
import warnings
import itertools
warnings.filterwarnings("ignore", category=UserWarning)
pd.options.mode.chained_assignment = None
%load_ext autoreload
%autoreload 2

In [6]:
output_dir='/Volumes/server/Projects/sfp_nsd/derivatives'
dset='nsdsyn'
subj='subj01'
roi='V1'
vs='pRFsize'

In [7]:
subj_df_path = os.path.join(output_dir, 'dataframes', dset, f'dset-{dset}_sub-{subj}_roi-{roi}_vs-{vs}.csv')
subj_df = pd.read_csv(subj_df_path)
subj_df.head()

stim_idx  image_idx     names  w_r  w_a  phase  class_idx  freq_lvl  voxel  \
0         0        104  pinwheel  0.0  6.0    0.0          0         0     10   
1         0        104  pinwheel  0.0  6.0    0.0          0         0     11   
2         0        104  pinwheel  0.0  6.0    0.0          0         0     12   
3         0        104  pinwheel  0.0  6.0    0.0          0         0     16   
4         0        104  pinwheel  0.0  6.0    0.0          0         0     17   

  task  ...  eccentricity     angle      size  visualrois  vroinames eccrois  \
0  avg  ...      1.556064  5.030775  0.971252         2.0         V1     3.0   
1  avg  ...      1.302301  4.925383  0.693124         2.0         V1     3.0   
2  avg  ...      1.081738  4.781199  0.559847         2.0         V1     3.0   
3  avg  ...      1.473532  4.971115  0.963097         2.0         V1     3.0   
4  avg  ...      1.495256  5.002201  0.945766         2.0         V1     3.0   

   local_sf  local_ori  hemi     sub  
0  0.613683   0.318386    lh  subj01  
1  0.733263   0.212994    lh  subj01  
2  0.882773   0.068810    lh  subj01  
3  0.648055   0.258726    lh  subj01  
4  0.638639   0.289812    lh  subj01  

[5 rows x 21 columns]

In [10]:
precision_path = os.path.join(output_dir, 'dataframes', dset, 'precision', f'precision-v_dset-{dset}_sub-{subj}_roi-{roi}_vs-{vs}.csv')
precision_df = pd.read_csv(precision_path)
precision_df.head()

sub  voxel vroinames  noise_SD  sigma_v_squared
0  subj01     10        V1  0.586458         0.409426
1  subj01     11        V1  0.438531         0.223560
2  subj01     12        V1  0.480373         0.264642
3  subj01     16        V1  0.718100         0.606524
4  subj01     17        V1  0.613964         0.451716

In [14]:
df = subj_df.merge(precision_df, on=['sub','voxel','vroinames'])

In [37]:
w_avg = df.groupby(['sub', 'voxel', 'class_idx', 'vroinames']).mean().reset_index()

In [56]:
pt_path = '/Volumes/server/Projects/sfp_nsd/derivatives/sfp_model/results_2D/test3.pt'

In [38]:
w_avg.pivot('voxel', 'class_idx', 'local_ori')

class_idx        0         1         2         3         4         5   \
voxel                                                                   
10         0.318386  0.318386  0.318386  0.318386  0.318386  0.318386   
11         0.212994  0.212994  0.212994  0.212994  0.212994  0.212994   
12         0.068810  0.068810  0.068810  0.068810  0.068810  0.068810   
16         0.258726  0.258726  0.258726  0.258726  0.258726  0.258726   
17         0.289812  0.289812  0.289812  0.289812  0.289812  0.289812   
...             ...       ...       ...       ...       ...       ...   
7086       0.309419  0.309419  0.309419  0.309419  0.309419  0.309419   
7087       0.270359  0.270359  0.270359  0.270359  0.270359  0.270359   
7089       0.271274  0.271274  0.271274  0.271274  0.271274  0.271274   
7090       0.276253  0.276253  0.276253  0.276253  0.276253  0.276253   
7091       0.296889  0.296889  0.296889  0.296889  0.296889  0.296889   

class_idx        6         7         8         9   ...        18        19  \
voxel                                              ...                       
10         2.674580  2.674580  2.674580  2.674580  ...  1.103784  1.103784   
11         2.569189  2.569189  2.569189  2.569189  ...  0.998392  0.998392   
12         2.425005  2.425005  2.425005  2.425005  ...  0.854208  0.854208   
16         2.614921  2.614921  2.614921  2.614921  ...  1.044124  1.044124   
17         2.646006  2.646006  2.646006  2.646006  ...  1.075210  1.075210   
...             ...       ...       ...       ...  ...       ...       ...   
7086       2.665613  2.665613  2.665613  2.665613  ...  1.094817  1.094817   
7087       2.626553  2.626553  2.626553  2.626553  ...  1.055757  1.055757   
7089       2.627468  2.627468  2.627468  2.627468  ...  1.056672  1.056672   
7090       2.632448  2.632448  2.632448  2.632448  ...  1.061652  1.061652   
7091       2.653083  2.653083  2.653083  2.653083  ...  1.082287  1.082287   

class_idx        20        21        22        23        24        25  \
voxel                                                                   
10         1.103784  1.103784  1.103784  1.103784  3.069371  2.279789   
11         0.998392  0.998392  0.998392  0.998392  2.963980  2.174398   
12         0.854208  0.854208  0.854208  0.854208  2.819796  2.030214   
16         1.044124  1.044124  1.044124  1.044124  3.009712  2.220129   
17         1.075210  1.075210  1.075210  1.075210  3.040797  2.251215   
...             ...       ...       ...       ...       ...       ...   
7086       1.094817  1.094817  1.094817  1.094817  3.060404  2.270822   
7087       1.055757  1.055757  1.055757  1.055757  3.021344  2.231762   
7089       1.056672  1.056672  1.056672  1.056672  3.022260  2.232677   
7090       1.061652  1.061652  1.061652  1.061652  3.027239  2.237657   
7091       1.082287  1.082287  1.082287  1.082287  3.047874  2.258292   

class_idx        26        27  
voxel                          
10         1.498575  0.708993  
11         1.393184  0.603601  
12         1.249000  0.459417  
16         1.438915  0.649333  
17         1.470001  0.680419  
...             ...       ...  
7086       1.489608  0.700026  
7087       1.450548  0.660966  
7089       1.451463  0.661881  
7090       1.456443  0.666860  
7091       1.477078  0.687496  

[2308 rows x 28 columns]

In [59]:
my_dataset = model.SpatialFrequencyDataset(w_avg, beta_col='betas')
my_model = model.SpatialFrequencyModel(full_ver=True)
loss_history, model_history, losses = model.fit_model(my_model, my_dataset,
                                                      save_path=pt_path,
                                                      learning_rate=0.001, max_epoch=3,
                                                      print_every=1, loss_all_voxels=False)

**epoch no.0 loss: 0.129
**epoch no.1 loss: 0.128
**epoch no.2 loss: 0.128
**epoch no.3: Finished! final model params...
 {'sigma': 0.0384337417781353, 'slope': 0.31463325023651123, 'intercept': 0.43112248182296753, 'p_1': 0.060593124479055405, 'p_2': 0.08446389436721802, 'p_3': 0.08890348672866821, 'p_4': 0.059790268540382385, 'A_1': 0.866459310054779, 'A_2': 0.883697509765625}
Elapsed time: 0.07 sec


In [60]:
import torch
another_model = model.SpatialFrequencyModel(full_ver=True)
another_model.load_state_dict(torch.load(pt_path))
another_model.eval()
for name, param in another_model.named_parameters():
    print(f'{name}: {param}')

sigma: Parameter containing:
tensor([0.0394], requires_grad=True)
slope: Parameter containing:
tensor([0.3156], requires_grad=True)
intercept: Parameter containing:
tensor([0.4321], requires_grad=True)
p_1: Parameter containing:
tensor([0.0616], requires_grad=True)
p_2: Parameter containing:
tensor([0.0854], requires_grad=True)
p_3: Parameter containing:
tensor([0.0879], requires_grad=True)
p_4: Parameter containing:
tensor([0.0588], requires_grad=True)
A_1: Parameter containing:
tensor([0.8656], requires_grad=True)
A_2: Parameter containing:
tensor([0.8828], requires_grad=True)


In [41]:
loss_history

epoch      loss
0      0  0.096106
1      1  0.095947

In [42]:
model_history

epoch     sigma     slope  intercept      p_1       p_2       p_3  \
0      0  0.619453  0.444037   0.691521  0.08782  0.044759  0.080649   
1      1  0.620453  0.443037   0.690521  0.08682  0.043759  0.081649   

        p_4       A_1       A_2  
0  0.071719  0.294542  0.939823  
1  0.072719  0.293542  0.938823

In [69]:
old_file='/Volumes/server/Projects/sfp_nsd/derivatives/sfp_model/results_2D/model_history_dset-nsdsyn_bts-mean_full_ver-True_subj01_lr-0.0005_eph-20000_V1.h5'
new_file='/Volumes/server/Projects/sfp_nsd/derivatives/sfp_model/results_2D/nsdsyn/model-history_lr-0.0005_eph-10000_dset-nsdsyn_sub-subj01_roi-V1_vs-pRFsize.h5'

In [70]:
old_f = pd.read_hdf(old_file)
new_f = pd.read_hdf(new_file)

In [71]:
old_f.query('epoch == 19999')

epoch     sigma     slope  intercept       p_1       p_2       p_3  \
19999  19999  2.464081  0.139384   0.215651  0.028885 -0.020794 -0.262531   

            p_4       A_1       A_2  
19999 -0.014679  0.021958 -0.003817

In [66]:
new_f.query('epoch == 9999')

epoch     sigma     slope  intercept      p_1       p_2       p_3  \
9999   9999  2.374602  0.146491   0.201589  0.02126 -0.020941 -0.254096   

           p_4       A_1       A_2  
9999 -0.015825  0.023916 -0.006775